export const types = {
  register: "[auth] Register a new user",
  login: "[auth] Login user",
  logout: "[auth] Logout user",
  loadUserData: "[auth] Load all user data",
  loadUserOrderId: "[auth] Load all user Order Id",
  loadProducts: "[cart] Load Content",
  userCart: "[cart] User Cart",
  addToCart: "[cart] Add Item To Cart",
  cleanCart: "[cart] Clean all cart's items",
  RemovefromCart: "[cart] Remove Item from Cart",
  repeatedItemfromCart: "[cart] Repeated Item from Cart",
  total: "[cart] Total To Pay",
  userData: "[cart] User's Data",
  payed: "[cart] Payed",
  order: "[cart] User's Order",
  orderId: "[cart] User's Order Id",
  orderDate: "[cart] User's Order Date",
  cleanUserData: "[cart] Clean User Data",
  showElement: "[ui] Show UI Element",
  closeElement: "[ui] Close UI Element",
  AddMsg: "[ui] Add Msg",
  RemoveMsg: "[ui] Remove Msg",
  loadAdminOrders: "[admin] Load Admin Orders",
  loadAdminFilterQuery: "[admin] Load Admin Filtered Query",
  loadAdminUsersData: "[admin] Load Admin Users Data",
  loadAdminEarned: "[admin] Load Admin Earned Data",
  loadMonthEarned: "[admin] Load Admin Month Earned Data",
  loadAdminUsers: "[admin] Load Admin Users",
  loadAdminMonthEarned: "[admin] Load Admin Monthly earned",
};
